# Generated by Django 5.2.7 on 2026-04-30 04:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormativaTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_normativa', models.CharField(max_length=150)),
                ('version_normativa', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('INACTIVA', 'Inactiva'), ('BORRADOR', 'Borrador')], default='VIGENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Normativa tributaria',
                'verbose_name_plural': 'Normativas tributarias',
                'db_table': 'normativas_tributarias',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('codigo_iso', models.CharField(max_length=5, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=20)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='FactorTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_factor', models.CharField(max_length=120)),
                ('valor_factor', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('INACTIVO', 'Inactivo')], default='VIGENTE', max_length=20)),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factores', to='appNuam.normativatributaria')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factores', to='appNuam.pais')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factores_creados', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Factor tributario',
                'verbose_name_plural': 'Factores tributarios',
                'db_table': 'factores_tributarios',
            },
        ),
        migrations.AddField(
            model_name='normativatributaria',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normativas', to='appNuam.pais'),
        ),
        migrations.CreateModel(
            name='InstrumentoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rut_emisor', models.CharField(max_length=20)),
                ('codigo_instrumento', models.CharField(max_length=50, unique=True)),
                ('nombre_instrumento', models.CharField(max_length=150)),
                ('tipo_instrumento', models.CharField(max_length=80)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='appNuam.pais')),
            ],
            options={
                'verbose_name': 'Instrumento financiero',
                'verbose_name_plural': 'Instrumentos financieros',
                'db_table': 'instrumentos_financieros',
            },
        ),
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tipo_archivo', models.CharField(max_length=20)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('registros_ok', models.PositiveIntegerField(default=0)),
                ('registros_error', models.PositiveIntegerField(default=0)),
                ('estado_proceso', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('PROCESADO', 'Procesado'), ('PROCESADO_CON_ERRORES', 'Procesado con errores'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_carga', to='appNuam.pais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_cargados', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Archivo de carga',
                'verbose_name_plural': 'Archivos de carga',
                'db_table': 'archivos_carga',
            },
        ),
        migrations.CreateModel(
            name='SesionAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_login', models.DateTimeField()),
                ('fecha_logout', models.DateTimeField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('EXPIRADA', 'Expirada')], default='ABIERTA', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Sesión de acceso',
                'verbose_name_plural': 'Sesiones de acceso',
                'db_table': 'sesiones_acceso',
            },
        ),
        migrations.CreateModel(
            name='ReglaConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_regla', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('condicion_aplicable', models.TextField()),
                ('formula_aplicable', models.TextField()),
                ('prioridad', models.PositiveIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_conversion', to='appNuam.normativatributaria')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_conversion', to='appNuam.pais')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_creadas', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Regla de conversión',
                'verbose_name_plural': 'Reglas de conversión',
                'db_table': 'reglas_conversion',
                'ordering': ['prioridad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('FINALIZADO', 'Finalizado'), ('ERROR', 'Error'), ('PARCIAL', 'Parcial')], default='INICIADO', max_length=20)),
                ('total_procesados', models.PositiveIntegerField(default=0)),
                ('total_error', models.PositiveIntegerField(default=0)),
                ('mensaje_resumen', models.TextField(blank=True, null=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='appNuam.archivocarga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_conversion', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Proceso de conversión',
                'verbose_name_plural': 'Procesos de conversión',
                'db_table': 'procesos_conversion',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto_origen', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('resultado_factor', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_calculado', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_calculo', models.DateTimeField()),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('EXPIRADA', 'Expirada'), ('ANULADA', 'Anulada'), ('BORRADOR', 'Borrador')], default='VIGENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_generadas', to='appNuam.archivocarga')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='appNuam.factortributario')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='appNuam.instrumentofinanciero')),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='appNuam.normativatributaria')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='appNuam.pais')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Calificación tributaria',
                'verbose_name_plural': 'Calificaciones tributarias',
                'db_table': 'calificaciones_tributarias',
            },
        ),
        migrations.CreateModel(
            name='BitacoraSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('modulo', models.CharField(max_length=80)),
                ('mensaje', models.TextField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora del sistema',
                'verbose_name_plural': 'Bitácora del sistema',
                'db_table': 'bitacora_sistema',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('registro_id', models.PositiveBigIntegerField()),
                ('accion', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de cambio',
                'verbose_name_plural': 'Auditorías de cambios',
                'db_table': 'auditoria_cambios',
            },
        ),
        migrations.CreateModel(
            name='DetalleCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.PositiveIntegerField()),
                ('dato_original', models.TextField()),
                ('estado_validacion', models.CharField(choices=[('VALIDO', 'Válido'), ('ERROR', 'Error'), ('OMITIDO', 'Omitido')], max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='appNuam.archivocarga')),
            ],
            options={
                'verbose_name': 'Detalle de carga',
                'verbose_name_plural': 'Detalles de carga',
                'db_table': 'detalle_carga',
                'unique_together': {('archivo', 'numero_fila')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='normativatributaria',
            unique_together={('pais', 'nombre_normativa', 'version_normativa')},
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='appNuam.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Rol',
                'verbose_name_plural': 'Usuario Roles',
                'db_table': 'usuario_roles',
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
