# Generated by Django 5.2.7 on 2026-05-17 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNuam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_pdf/')),
                ('tipo_documento', models.CharField(choices=[('pdf', 'PDF'), ('imagen', 'Imagen'), ('scan', 'Escaneo')], default='pdf', max_length=20)),
                ('estado', models.CharField(choices=[('subido', 'Subido'), ('procesando', 'Procesando'), ('extraido', 'Extraído'), ('validado', 'Validado'), ('error', 'Error')], default='subido', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='appNuam.pais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to='appNuam.usuario')),
            ],
            options={
                'verbose_name': 'Documento digital',
                'verbose_name_plural': 'Documentos digitales',
                'db_table': 'documentos_digitales',
            },
        ),
        migrations.CreateModel(
            name='DocumentoExtraido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_extraido', models.TextField()),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('instrumento', models.CharField(blank=True, max_length=120, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraccion', to='appNuam.documentodigital')),
            ],
            options={
                'db_table': 'documentos_extraidos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_original', models.TextField(blank=True, null=True)),
                ('valor_corregido', models.TextField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appNuam.documentodigital')),
                ('usuario_validador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
