# Generated by Django 5.2.7 on 2026-05-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNuam', '0002_documentodigital_documentoextraido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=150)),
                ('tiporegla', models.CharField(choices=[('CALCULO', 'Cálculo'), ('VALIDACION', 'Validación'), ('SCHEDULING', 'Scheduling'), ('EXPORTACION', 'Exportación')], max_length=20)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('prioridad', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(default=dict)),
                ('vigentedesde', models.DateField()),
                ('vigentehasta', models.DateField(blank=True, null=True)),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='appNuam.normativatributaria')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs', to='appNuam.reglaconversion')),
            ],
            options={
                'db_table': 'normativas_config',
                'ordering': ['tiporegla', 'prioridad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regimen', models.CharField(choices=[('GENERAL', 'General'), ('SIMPLIFICADO', 'Simplificado'), ('ESPECIAL', 'Especial')], max_length=30)),
                ('actividad', models.CharField(blank=True, max_length=120, null=True)),
                ('atributos', models.JSONField(blank=True, default=dict)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfilestributarios', to='appNuam.pais')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfiltributario', to='appNuam.usuario')),
            ],
            options={
                'db_table': 'perfilestributarios',
            },
        ),
        migrations.CreateModel(
            name='ObligacionTributariaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoobligacion', models.CharField(max_length=80)),
                ('nombreobligacion', models.CharField(max_length=150)),
                ('periodicidad', models.CharField(max_length=20)),
                ('fechavencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GENERADA', 'Generada'), ('CUMPLIDA', 'Cumplida'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligacionesprogramadas', to='appNuam.normativatributaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligacionestributarias', to='appNuam.usuario')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='appNuam.perfiltributario')),
            ],
            options={
                'db_table': 'obligacionestributariasprogramadas',
            },
        ),
        migrations.CreateModel(
            name='PlantillaExportacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=150)),
                ('formato', models.CharField(choices=[('XML', 'XML'), ('JSON', 'JSON')], max_length=10)),
                ('schema', models.JSONField(default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillasexportacion', to='appNuam.normativatributaria')),
            ],
            options={
                'db_table': 'plantillasexportaciontributaria',
            },
        ),
    ]
